name: Generate Ansible Moudle Documentation

# version: v18

on:
  push:
    paths:
      - '.github/workflows/ansible_doc.yml'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependency
        run: pip install -r requirements.txt

      - name: install ansible
        run: pip install ansible=5.3

      - name: Generate Ansible Doc
        run: |
          mkdir docs
          poetry run python gen_ansible_doc.py docs

      - name: Gen zip files
        run: |
          zip -r ansible_doc.zip docs
